(WIP) More ItemGroups
NCBPFluffyBear/SlimeCustomizer pull request #41
Opened 2022-09-15 19:05 UTC by ybw0014

2022-09-15 20:06 UTC, ybw0014 commented
Just noticed there is a formatting pr. Would you like to merge that first?

2022-10-22 05:28 UTC, ybw0014 commented
> Tested this. It works perfectly! The only issue was that before you could use all caps in category names but now you can no longer do that. Like you can no longer use PHOENIX_GEAR but you gotta use phoenix_gear. I think that is intended though but not sure.

I've made some mistakes. Should use the original category id as key instead of lowercased category id.
I will push this change asap.

2022-10-24 16:33 UTC, NCBPFluffyBear commented
I will wait a bit to see if there are any changes to the formatting pr. If it is not finished yet I will merge this. Thank you for your contribution.

2022-11-02 16:41 UTC, NCBPFluffyBear requested changes
Forgot to release this review

2022-11-02 18:22 UTC, merged